# Generated by Django 4.1.7 on 2023-02-25 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=500, null=True)),
                ("photo", models.ImageField(upload_to="about/")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=50, unique=True)),
                ("position", models.SmallIntegerField(unique=True)),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=24)),
                ("zipcode", models.PositiveIntegerField()),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Error phone number",
                                regex="^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("topic", models.CharField(max_length=250)),
                ("message", models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=50, unique=True)),
                ("position", models.SmallIntegerField(unique=True)),
                ("desc", models.TextField(blank=True, max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("photo", models.ImageField(default=None, upload_to="events/%Y-%m-%d")),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(default=None, upload_to="")),
                ("title", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Error phone number",
                                regex="^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$",
                            )
                        ],
                    ),
                ),
                ("persons", models.SmallIntegerField()),
                ("message", models.TextField(blank=True, max_length=250)),
                ("date", models.DateField(auto_now_add=True)),
                ("date_processing", models.DateField(auto_now=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(default=None, upload_to="")),
                ("name", models.CharField(max_length=30)),
                ("role", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(default=None, upload_to="")),
                ("name", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=30)),
                ("rating", models.IntegerField()),
                ("testimonial", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WhyUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("position", models.SmallIntegerField(unique=True)),
                ("description", models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=120, unique=True)),
                ("ingredients", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default=None, upload_to="dishes/%Y-%m-%d"
                    ),
                ),
                ("is_special", models.BooleanField(default=False)),
                ("position", models.SmallIntegerField(unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "position"),
            },
        ),
    ]
